work_dir: ./work_dir/snr/pretrain

# feeder
feeder: feeder.Feeder_snr
train_feeder_args:
  data_path: ./data/train.pkl
  mode: double

# model
model: net.CNN
model_args:
  channels: 13
  num_classes: 3

# byol
moving_average_decay: 0.99
projection_size: 256
projection_hidden_size: 512
K: 512
tt: 0.03
ot: 0.1
drop_percent: 0.2

#optim
optimizer: 'Adam'
weight_decay: 1e-5
base_lr: 1e-2
step: [10, 50]

# training
device: 0
batch_size: 64 
test_batch_size: 64
num_epoch: 150
nesterov: True